---
title: "examples"
author: "Julia Lee"
date: "3/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# dashboard example from stackoverflow 
```{r}
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Simple tabs"),
  dashboardSidebar(
    sidebarMenu(id = "tabs",
      menuItem("Menu Item 1", tabName = "one", icon = icon("dashboard")),
      menuItem("Menu Item 1", tabName = "two", icon = icon("th"))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "one",h2("Dashboard tab content"),actionButton('switchtab', 'Switch tab')),
      tabItem(tabName = "two",h2("Widgets tab content"))
    )
  )
)

server <- function(input, output, session) {
  observeEvent(input$switchtab, {
    newtab <- switch(input$tabs, "one" = "two","two" = "one")
    updateTabItems(session, "tabs", newtab)
  })
}

shinyApp(ui, server)

```



```{r}

data_sets <- c("mtcars", "morley", "rock")

server<-shinyServer(function(input, output) {

  # Drop-down selection box for which data set
  output$choose_dataset <- renderUI({
    selectInput("dataset", "Data set", as.list(data_sets))
  })

  # Check boxes
  output$choose_columns <- renderUI({
    # If missing input, return to avoid error later in function
    if(is.null(input$dataset))
      return()

    # Get the data set with the appropriate name
    dat <- get(input$dataset)
    colnames <- names(dat)

    # Create the checkboxes and select them all by default
    checkboxGroupInput("columns", "Choose columns", 
                        choices  = colnames,
                        selected = colnames)
  })


  # Output the data
  output$data_table <- renderTable({
    # If missing input, return to avoid error later in function
    if(is.null(input$dataset))
      return()

    # Get the data set
    dat <- get(input$dataset)

    # Make sure columns are correct for data set (when data set changes, the
    # columns will initially be for the previous data set)
    if (is.null(input$columns) || !(input$columns %in% names(dat)))
      return()

    # Keep the selected columns
    dat <- dat[, input$columns, drop = FALSE]

    # Return first 20 rows
    tail(dat, 20)
     output$downloadData <- downloadHandler(
    filename = function() { paste(input$dat, '.csv', sep='') },
    content = function(file) {
      write.csv(datasetInput(), file)
    }
  )
  })
})
```

# example about how to download data 
```{r}
ui<-shinyUI(pageWithSidebar(

  headerPanel(""),

  sidebarPanel(
    uiOutput("choose_dataset"),

    uiOutput("choose_columns"),
    br(),
    a(href = "https://gist.github.com/4211337", "Source code"),
     downloadButton('downloadData', 'Download')
  ),


  mainPanel(
    tableOutput("data_table")
  )
))
shinyApp(ui, server)
```
