---
title: "Shiny fun"
author: "Julia Lee"
date: "2/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RMySQL)
#install.packages("sf")
library(sf)
#install.packages("macleish")
library(leaflet)
library(RSQLite)
install.packages("ceeds")
library(ceeds)
#install.packages("lwgeom")
library(lwgeom)
#devtools::install_github("beanumber/macleish")
library(macleish)
#packageVersion("macleish")
#install.packages("shiny")
#install.packages("shinydashboard")
library(shinydashboard)
library(shiny)
```

```{r}
etl_transform.etl_macleish
```

```{r}
whately_2015<- whately_2015
macleish <- etl("macleish")
macleish %>%
  etl_update()
whately_update <- macleish %>%
  tbl("whately")
names(whately_update)
```





```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Wind Speed"),
  dashboardSidebar(),
  dashboardBody(
    # Boxes need to be put in a row (or column)
    fluidRow(
      box(plotOutput("plot1", height = 250)),

      box(
        title = "Controls",
        sliderInput("slider", "Number of observations:", 1, 200, 100)
      )
    )
  )
)

server <- function(input,output) {
  output$plot1 <- renderPlot({
    ggplot(whately_2015, aes(x=wind_speed)) + 
  geom_histogram(binwidth=1)
  })
}

shinyApp(ui, server)
```





```{r}
read_whately()

whately %>%
  mutate(the_year = strftime('%Y', when)) %>%
  group_by(the_year) %>%
  summarize(N = n(), begin = min(when), end = max(when), avg_temp = mean(temperature))
orchard <- macleish %>%
  tbl("orchard")
orchard %>%
  mutate(the_year = strftime('%Y', when)) %>%
  group_by(the_year) %>%
  summarize(N = n(), begin = min(when), end = max(when), avg_temp = mean(temperature))

daily <- whately %>%
  mutate(the_date = date(when)) %>%
  group_by(the_date) %>%
  summarize(N = n(), avgTemp = mean(temperature)) %>%
  collect()
```

```{r}
ggplot(data = daily, aes(x = as.Date(the_date), y = avgTemp)) +
  geom_point() + geom_smooth()
```
